### ISSUE TITLE
worker/runner does not handle command with `./` in front of the command name

### ISSUE THREAD

**Issue by tdyas** [buildbarn/bb-remote-execution#70] opened 2020-08-30 06:19 UTC
I am attempting to get [Pants](https://github.com/pantsbuild/pants) integrated with the [remote-apis-testing project](https://gitlab.com/remote-apis-testing/remote-apis-testing). The integration work is on this branch: https://gitlab.com/tdyas/remote-apis-testing/-/tree/pants_client_support

Pants probes the remote execution environment to find the location of Python interpreters [by running a remote execution request](https://github.com/pantsbuild/pants/blob/cf483ead6d4d4a4cc4fc4ae18e3b5b633509d933/src/python/pants/engine/process.py#L353-L366). The command passed to the server has "./script.sh" as the name of the command (with `script.sh` provided in the input root). 

Buildbarn rejects the request with the following error:

```
 Exception: Error from remote execution: 3-INVALID_ARGUMENT: "Failed to create input directory \".\": Invalid filename: \".\""
```

This should reproduce on my remote-apis-testing branch if you run: `cd docker && ./run.sh -s docker-compose-buildbarn.yml -c docker-compose-pants.yml`

Any advice on why Buildbarn is generating this error? The path technically is a path relative to the input root and should be in spec, which states: 

>  // The arguments to the command. The first argument must be the path to the
>  // executable, which must be either a relative path, in which case it is
>  // evaluated with respect to the input root, or an absolute path.

https://github.com/bazelbuild/remote-apis/blob/5a7b1a472165a0ea47b9060089855385fe351193/build/bazel/remote/execution/v2/remote_execution.proto#L456-L458

*This of course assumes that the "./script.sh" as the command is the cause. It was definitely this request though because the Pants debug logging shows that this was the request that was sent.)

**Comment by EdSchouten** [comment] 2020-08-30 06:24
At first glance, this looks like a bug in Pants to me. The error message that you pasted, gets generated by Buildbarn here:

https://github.com/buildbarn/bb-remote-execution/blob/9bb5474ac5f08b10c6118ba2954288585d62eef4/pkg/builder/naive_build_directory.go#L92-L94

In this case the issue is not that Command.arguments contains a leading "./". It's that the input root contains an actual entry with name ".". That's obviously incorrect. Pants shouldn't be emitting such input roots.

**Comment by EdSchouten** [comment] 2020-08-30 07:39
Thanks for working towards getting this fixed in Pants! Let's close this issue, so we can continue discussing this there.

**Closed by EdSchouten** 2020-08-30 07:39 UTC

**Comment by tdyas** [comment] 2020-08-30 16:52
I've worked around this particular issue in Pants with https://github.com/pantsbuild/pants/pull/10706, although Pants definitely code needs better validation to ensure invalid filenames cannot be generated.

**Comment by tdyas** [comment] 2020-08-31 19:04
I can open as a new issue but with my latest work on https://gitlab.com/tdyas/remote-apis-testing/-/tree/pants_client_support, Buildbarn now fails with a different error but still seems related to the `./` issue. Note that Buildfarm and Buildgrid both now pass.

```
client_1  |   Exception: Too many failures from server. The last error was: Failed to run command: Failed to start process: fork/exec ./script.sh: exec format error
```

**Comment by tdyas** [comment] 2020-08-31 19:53
And might be a Pants bug due to leading newline before the shebang. Will fix that and see what occurs. I'm confused then as to why Buildgrid and Buildfarm pass.

**Comment by EdSchouten** [comment] 2020-08-31 21:30
Buildbarn runs command using execve(). It may be the case that Buildgrid and Buildfarm use a shell. Shells tend to have logic in place to catch ENOEXEC run the executable as if it were a shell script.

Notice how my shell (zsh) runs a shell script, even if it lacks a shebang:

```
$ cat foo.sh                            
echo hi
$ ./foo.sh 
hi
```

Now let me create this launcher utility:

```c
#include <stdio.h>
#include <unistd.h>

char **environ;

int main() {
	char *argv[] = {"./foo.sh", NULL};
	execve("./foo.sh", argv, environ);
	perror("execve");
}
```

Let's run foo.sh using this launcher:

```
$ cc -o bla bla.c
$ ./bla   
execve: Exec format error
```

As soon as I add a proper shebang to foo.sh, the launcher tool is capable of running the script properly.
