### ISSUE TITLE
Instance name lost when ExecuteRequest arrives in scheduler

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbarn/bb-remote-execution#76] opened 2020-12-05 17:03 UTC
We have a Goma/Buildbarn configuration, and I am currently testing an upgrade of the system

The Goma system uses the instance name "goma", and the storage and workers are configured for this name (and only this name).

During testing requests failed with '`No workers exist for instance "" `' for the specified platform.

Testing so far has shown that the Goma server backend (which is connected to the storage with a unix socket, as are the buildbarn backend components to each other)  correctly configures "goma" as the instance name for the ExecuteRequest message.

However, when this message arrives in the `pkg/builder/in_memory_build_queue.go`  function Execute(), in.InstanceName is an empty string. This suggest that the value is lost somewhere along the gome->storage->scheduler transmission chain. I did notice some possible locations for the problem, but the apparent lack of functionality for activity logging in the backend has so far prevented detailed debugging.

At present, during testing, I am working around this issue by forcing the instance name to "goma", and I could make that permanent until a fix by creating a branch of the repo, but I would rather avoid that.

For reference, the checkouts are currently:

-  bb-remote-execution:  ee554d7a 
-  bb-storage: a89a0279
-  bb-browser: 61b07488

**Comment by EdSchouten** [comment] 2020-12-05 17:04
Hey! Did you make sure to set this Config option?

https://github.com/buildbarn/bb-storage/blob/master/pkg/proto/configuration/builder/builder.proto#L18

**Comment by YngveNPettersen** [comment] 2020-12-05 17:28
Not AFAICT, I have a `goma: {endpoint; {}}` in the schedulers section; IMO that should be sufficient.

AFAICT, there is no mention of this in any of the examples; Which reminds me: There seems to be no examples which presents **all** the settings, which means that the only way to find them is to dig through proto files where the names does not match the names used in the config files. As an example: Figuring out the new local storage configuration took several days, and that was with a fairly detailed example being available, but which still left out a number of guidelines for values.

Additionally: removing the instance name specified by the requester is IMNSHO a serious bug. Having a different instance as an **override** possibility, maybe, but the default should be to forward unchanged.

**Comment by EdSchouten** [comment] 2020-12-05 17:31
You need to explicitly re-add it. See this line in the docs:

https://github.com/buildbarn/bb-storage/blob/master/pkg/proto/configuration/bb_storage/bb_storage.proto#L30

Contributions to improve docs, example deployments, etc. are more than welcome!

**Comment by YngveNPettersen** [comment] 2020-12-05 17:52
My point is that the README, or an associates file, in each repository need to list **every** available setting, and their allowed variations, for the configuration of the software.

One possibility could to auto-generate this from the proto-files, along with the comments for the field, but then the documentation there probably needs to somehow specify valid examples.

**Comment by YngveNPettersen** [comment] 2020-12-05 17:59
As for removing the instance name: As mentioned above, I consider that a bug **unless, and only unless,** an override is explicitly added by the user.

**Comment by EdSchouten** [comment] 2020-12-06 11:14
> As for removing the instance name: As mentioned above, I consider that a bug **unless, and only unless,** an override is explicitly added by the user.

We want to have facilities for:

- Removing prefixes from instance names
- Adding prefixes to instance names
- Substituting prefixes on instance names

We solve this by letting the map key be used to determine what needs to be stripped, and the message inside the map hold a string that is prepended. Two options that are orthogonal to each other.

The issue is that Protobuf v3 doesn’t make any distinctions between the zero value (“”, 0, false) and unset values for scalar fields. This means that there is no way we can distinguish this option being unset, or the user explicitly requesting that no prefix is added. There is thus little we can improve, apart from switching away from Protobuf for the configuration schema, which is absolutely out of the question.

Also with regards to providing ‘better defaults’: Buildbarn doesn’t tend to use default values, for the reason that default values are more often wrong than right. Everybody has a completely different workload, and operates Buildbarn at a different scale. People apparently want to run Buildbarn on Raspberry Pis, but there are also people who run clusters that have storage setups with more than 1 PB of space. What works right for me most certainly doesn’t work right for you.

So far the motto has been to make as much as possible self-tuning/untunable, but for the remaining sets of options, I do want the users to make a conscious decision. This will require more effort up front (as you stated, to figure out how LocalBlobAccess needs to be set up), but hopefully that time wasn’t wasted. I suppose you now have a better understanding of how LocalBlobAccess works and have enough knowledge to also debug any issues you have with it. The last thing I want is that Buildbarn becomes this mysterious black box. One that works perfectly fine, up until the point where it simply doesn’t.

I’m closing this issue, as the original question has been answered. Feel free to open other issues/send pull requests for any of the other topics that were discussed. Thanks!

**Closed by EdSchouten** 2020-12-06 11:14 UTC
